[package]
name = "guac"
version = "0.1.0"
authors = ["Jacob Henn <windowWeasel@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
crossterm = "0.23"
colored = "2"
num = "0.4"
argh = "0.1"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
